CREATE TABLE COMMENTS
(
    NUM       NUMBER PRIMARY KEY,
    ID        VARCHAR2(30) REFERENCES MEMBER (ID),
    CONTENT   VARCHAR2(200),
    REG_DATE  DATE,
    BOARD_NUM NUMBER REFERENCES BOARD (BOARD_NUM) ON DELETE CASCADE
);

drop sequence com_seq;
create sequence com_seq;